---
- name: run authconfig
  command: /usr/sbin/authconfig --enablemkhomedir --enableldap --enableldapauth --ldapserver={{ ldap_uri }} --ldapbasedn={{ basedn }} --updateall

- name: restart sshd
  service: name=sshd state=restarted
