---
- name: determine if running in Docker
  stat: path=/vct
  register: vct_dir

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download RPMs
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS6/{{ item.path }}
           dest=/var/tmp/{{ item.path }}
           sha256sum={{ item.sha256 }}
  with_items:
    - { path: mercurial-3.4.1-0.x86_64.rpm, sha256: 4e6190232ae217aacc894c0baf8e61900cb55d4ee0406a09a22b70cb9c6dfbd0 }
    - { path: mod_wsgi-4.4.8-1.el6.x86_64.rpm, sha256: e2f7e3daad0db47aa875a56a24a2132e5b33211fe78c8bf7b15d6d9bcf0a3cc5 }

# Measurements revealed that the yum module is slow and adds a few seconds
# overhead to invocations. So, we use low-level commands, which execute
# much faster.
- name: System packages installed
  command: /usr/bin/yum -y install openldap-clients openldap-devel sudo syslog /var/tmp/mercurial-3.4.1-0.x86_64.rpm /var/tmp/mod_wsgi-4.4.8-1.el6.x86_64.rpm

- name: Python package dependencies
  pip: requirements={{ vct }}/ansible/roles/hg-reviewboard/files/requirements.txt

- name: Source code groups
  group: name={{ item.name }} gid={{ item.gid }}
  with_items:
    - { name: 'scm_level_1', gid: 673 }
    - { name: 'scm_level_2', gid: 685 }
    - { name: 'scm_level_3', gid: 679 }
    - { name: 'scm_l10n', gid: 678 }
    - { name: 'scm_l10n_infra', gid: 680 }
    - { name: 'scm_sec_sensitive', gid: 686 }
    - { name: 'scm_ecmascript', gid: 687 }

- name: Create hg user
  user: name=hg uid=500 shell=/bin/bash comment='Hg user' groups=scm_level_1,scm_level_2,scm_level_3,scm_l10n,scm_l10n_infra,scm_sec_sensitive

- name: Repository directories present
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /repo
    - /repo/hg
    - /repo/hg/library
    - /repo/hg/mozilla
    - /repo/hg/webroot_wsgi

- name: set up version-control-tools repo (server only)
  hg: repo=https://hg.mozilla.org/hgcustom/version-control-tools
      dest=/repo/hg/version-control-tools
      revision={{ lookup('file', '../../../../.vctnode') }}
      force=yes
      purge=yes
  when: vct_dir.stat.exists == False

# The hg module's purge doesn't delete ignored files. Boo. Force that
# because old .pyc files may cause chaos.
- name: delete ignored files from version-control-tools repo
  command: hg --config extensions.purge= -R /repo/hg/version-control-tools purge --all
  when: vct_dir.stat.exists == False

- name: synchronize version-control-tools (Docker only)
  synchronize: src={{ vct | mandatory }}/
               dest=/repo/hg/version-control-tools/
               recursive=yes
               delete=yes
  when: vct_dir.stat.exists == True
  tags:
    - docker-refresh

#- name: hg scripts are in place
#  hg: dest=/repo/hg/scripts repo=https://hg.mozilla.org/hgcustom/hgscripts

- name: Global hgrc installed
  template: src=hgrc.j2 dest=/etc/mercurial/hgrc mode=0444

- name: Install pash
  template: src={{ item }}.j2 dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
    - hg_helper.py
    - ldap_helper.py
    - pash.py
    - sh_helper.py
  tags: docker-startup

- name: Install pash wrapper
  copy: src=pash_wrapper dest=/usr/local/bin/pash_wrapper mode=0755

- name: hgweb wsgi and config in place
  copy: src={{ item }} dest=/repo/hg/webroot_wsgi/{{ item }}
  with_items:
    - hgweb.config
    - hgweb.wsgi

- name: Apache vhost config in place
  template: src=vhost.conf.j2 dest=/etc/httpd/conf.d/hg.conf

- name: Apache log directory present
  file: path=/var/log/httpd/{{ domain | mandatory }} state=directory mode=0755

- name: Prune system httpd configs
  file: path=/etc/httpd/conf.d/welcome.conf state=absent

- include: discovery-repo.yml repo=autoreview
