---
- name: install supervisor config
  copy: src=supervisor-docker.conf
        dest=/etc/supervisor.d/docker.conf
        owner=root
        group=root
        mode=0644

# Docker doesn't have full TTYs. sudo will fail unless we remove the
# requirement that a TTY be present.
- name: Remove SSH TTY requirement
  replace: dest=/etc/sudoers regexp='^Defaults    requiretty.*$' replace=''

- name: install support scripts
  copy: src={{ item }} dest=/{{ item }} mode=0755
  with_items:
    - create-repo
    - set-hgrc-option
    - set-ldap-property
    - set-mirrors.py

# While this file contains credentials, it needs to be world readable
# because pash is executed as a regular user, since it is what runs as
# the SSH command. We rely on pash's and Mercurial's security to not
# divulge its contents.
- name: install LDAP configuration for pash
  copy: src=ldap.json
        dest=/etc/mercurial/ldap.json
        owner=root
        group=root
        mode=0644

- name: Install entrypoint script
  copy: src=entrypoint.py dest=/entrypoint.py mode=0755

- name: virtualenv to run test-specific processes
  include: ../../../tasks/virtualenv.yml
           venv=/var/hg/venv_testing
           requirements=../roles/docker-hg-ssh/files/requirements-testing.txt
