---
- name: Generate replication SSH key
  command: /usr/bin/ssh-keygen -b 2048 -f /etc/mercurial/mirror -t rsa

- name: Proper permissions on replication private key
  file: path={{ item }} owner=hg group=hg
  with_items:
    - /etc/mercurial/mirror
    - /etc/mercurial/mirror.pub

- name: hg authorized keys is present
  command: /bin/cp /etc/mercurial/mirror.pub /home/hg/.ssh/authorized_keys

# Docker doesn't have full TTYs. sudo will fail unless we remove the
# requirement that a TTY be present.
- name: Remove SSH TTY requirement
  replace: dest=/etc/sudoers regexp='^Defaults    requiretty.*$' replace=''

- name: Create create-repo script
  copy: src=create-repo dest=/create-repo mode=0755

- name: Create set-mirrors script
  copy: src=set-mirrors.py dest=/set-mirrors.py mode=0755
