---
# Docker doesn't have full TTYs. sudo will fail unless we remove the
# requirement that a TTY be present.
- name: Remove SSH TTY requirement
  replace: dest=/etc/sudoers regexp='^Defaults    requiretty.*$' replace=''

- name: Create create-repo script
  copy: src=create-repo dest=/create-repo mode=0755

- name: Create set-mirrors script
  copy: src=set-mirrors.py dest=/set-mirrors.py mode=0755

- name: Install pash
  copy: src={{ vct }}/scripts/pash/{{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
    - hg_helper.py
    - ldap_helper.py
    - pash.py
    - repo_group.py
    - sh_helper.py

- name: Install repo-push script
  copy: src={{ vct }}/scripts/repo-push.sh dest=/usr/local/bin/repo-push.sh mode=0755

- name: Install push scripts
  copy: src={{ vct }}/scripts/{{ item }} dest=/repo/hg/scripts/{{ item }} mode=0755
  with_items:
    - record-pushes.sh
    - push-repo.sh

# While this file contains credentials, it needs to be world readable
# because pash is executed as a regular user, since it is what runs as
# the SSH command. We rely on pash's and Mercurial's security to not
# divulge its contents.
- name: install LDAP configuration for pash
  copy: src=ldap.json
        dest=/etc/mercurial/ldap.json
        owner=root
        group=root
        mode=0644

- name: Install entrypoint script
  copy: src=entrypoint.py dest=/entrypoint.py mode=0755
