---
- name: Generate replication SSH key
  command: /usr/bin/ssh-keygen -b 2048 -f /etc/mercurial/mirror -t rsa creates=/etc/mercurial/mirror

- name: Proper permissions on replication private key
  file: path={{ item }} owner=hg group=hg
  with_items:
    - /etc/mercurial/mirror
    - /etc/mercurial/mirror.pub

- name: hg authorized keys is present
  command: /bin/cp /etc/mercurial/mirror.pub /home/hg/.ssh/authorized_keys

# Docker doesn't have full TTYs. sudo will fail unless we remove the
# requirement that a TTY be present.
- name: Remove SSH TTY requirement
  replace: dest=/etc/sudoers regexp='^Defaults    requiretty.*$' replace=''

- name: Create create-repo script
  copy: src=create-repo dest=/create-repo mode=0755

- name: Create set-mirrors script
  copy: src=set-mirrors.py dest=/set-mirrors.py mode=0755

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - /usr/local/bin
    - /repo/hg/extensions
    - /repo/hg/extensions/bundleclone
    - /repo/hg/extensions/pushlog
    - /repo/hg/extensions/parsedatetime
    - /repo/hg/extensions/serverlog
    - /repo/hg/libraries
    - /repo/hg/libraries/mozhghooks
    - /repo/hg/scripts

- name: Install pash
  copy: src={{ vct }}/scripts/pash/{{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
    - hg_helper.py
    - ldap_helper.py
    - pash.py
    - repo_group.py
    - sh_helper.py

- name: Install repo-push script
  copy: src={{ vct }}/scripts/repo-push.sh dest=/usr/local/bin/repo-push.sh mode=0755

- name: Install pushlog web extensions
  copy: src={{ vct }}/hgext/pushlog-legacy/{{ item }} dest=/repo/hg/extensions/{{ item }}
  with_items:
    - buglink.py
    - feedparser.py
    - hgwebjson.py
    - pushlog-feed.py
    - parsedatetime/__init__.py
    - parsedatetime/parsedatetime.py
    - parsedatetime/parsedatetime_consts.py

- name: Install pushlog extension
  copy: src={{ vct }}/hgext/pushlog/__init__.py dest=/repo/hg/extensions/pushlog/__init__.py

- name: Install serverlog extension
  copy: src={{ vct }}/hgext/serverlog/__init__.py dest=/repo/hg/extensions/serverlog/__init__.py

- name: install bundleclone extension
  copy: src={{ vct }}/hgext/bundleclone/__init__.py dest=/repo/hg/extensions/bundleclone/__init__.py

- name: install pushrebase extension
  copy: src={{ vct }}/hgext/pushrebase/__init__.py dest=/repo/hg/extensions/pushrebase.py

- name: install hooks
  copy: src={{ vct }}/hghooks/mozhghooks/{{ item }} dest=/repo/hg/libraries/mozhghooks/{{ item }} owner=root group=root mode=0644
  with_items:
    - changelog_correctness.py
    - commit-message.py
    - prevent_case_only_renames.py
    - prevent_idl_change_without_uuid_bump.py
    - prevent_string_changes.py
    - prevent_uuid_changes.py
    - prevent_webidl_changes.py
    - push_printurls.py
    - single_head_per_branch.py
    - single_root.py
    - treeclosure.py
    - treeclosure_comm_central.py
    - try_mandatory.py
    - whitelist_qa.py
    - whitelist_releng.py

- name: ensure mozhghooks directory is importable
  file: path=/repo/hg/libraries/mozhghooks/__init__.py
        state=touch
        owner=root
        group=root
        mode=0644

- name: Install push scripts
  copy: src={{ vct }}/scripts/{{ item }} dest=/repo/hg/scripts/{{ item }} mode=0755
  with_items:
    - record-pushes.sh
    - push-repo.sh

# While this file contains credentials, it needs to be world readable
# because pash is executed as a regular user, since it is what runs as
# the SSH command. We rely on pash's and Mercurial's security to not
# divulge its contents.
- name: install LDAP configuration for pash
  copy: src=ldap.json
        dest=/etc/mercurial/ldap.json
        owner=root
        group=root
        mode=0644

- name: Install entrypoint script
  copy: src=entrypoint.py dest=/entrypoint.py mode=0755
