---
dependencies:
  - ius-repo
  - supervisor
  - {
      role: openssh-lpk,
      home_attribute: fakeHome,
      accept_env: "AUTOLAND_REQUEST_USER LANG LC_ALL LC_MESSAGES",
      force_command: /usr/local/bin/pash_wrapper,
      # By default, SSH limits to 10 concurrent connections for
      # individual users. This may interfere with replication if
      # multiple replication events are in progress. So we up the limit.
      # See bug 1038478.
      max_startups: 50,
      max_sessions: 50,
    }
  - {
      role: kafka-broker,
      kafka_host_name: "{{ inventory_hostname }}",
      kafka_broker_id: "{{ zk_servers[inventory_hostname] }}",
      when: "{{ inventory_hostname in zk_servers }}",
    }
