---
dependencies:
  - ius-repo
  - {
      role: openssh-lpk,
      home_attribute: fakeHome,
      force_command: /usr/local/bin/pash_wrapper,
      # By default, SSH limits to 10 concurrent connections for
      # individual users. This may interfere with replication if
      # multiple replication events are in progress. So we up the limit.
      # See bug 1038478.
      max_startups: 50,
      max_sessions: 50,
    }
