---
- name: Install Docker support scripts
  copy: src={{ item }} dest=/{{ item }} mode=0755
  with_items:
    - create-repo
    - entrypoint.py
    - kill-wsgi-procs
    - refresh
    - run.sh
    - set-strip-users
    - set-urls

- name: Install psutil
  pip: name=psutil
