---
- name: Install Docker support scripts
  copy: src={{ item }} dest=/{{ item }} mode=0755
  with_items:
    - create-repo
    - entrypoint.py
    - kill-wsgi-procs
    - refresh
    - run.sh
    - set-strip-users
    - set-urls

- name: Install psutil
  pip: name=psutil

- name: Configure MozReview user
  ini_file: dest=/etc/mercurial/hgrc section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
  with_items:
    - { section: reviewboard, option: username, value: mozreview }
    - { section: reviewboard, option: password, value: password }
