---
vct_repo: "https://hg.mozilla.org/hgcustom/version-control-tools"
rev: "@"


secrets:
    mozreview_token: "default_token"

    bugzilla_user: "default_user"
    bugzilla_password: "default_password"

    db_name: "default_name"
    db_user: "default_user"
    db_password: "default_password"
    db_host: "default_host"

    ldap_user: "default_ldap_user@default"
    ssh_key_name: "id_rsa"

repos: {}
