---
# TODO Ansible isn't recognizing systemd services?
- name: restart rsyslogd
  service: name=rsyslog state=restarted
  ignore_errors: True

- name: systemd daemon reload
  command: /usr/bin/systemctl daemon-reload
  ignore_errors: True

- name: restart nrpe.service
  service: name=nrpe.service
           state=restarted
  ignore_errors: True
