---

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download Mercurial package
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS6/mercurial-3.4.1-0.x86_64.rpm
           dest=/var/tmp/mercurial-3.4.1-0.x86_64.rpm
           sha256sum=4e6190232ae217aacc894c0baf8e61900cb55d4ee0406a09a22b70cb9c6dfbd0

# The yum module is slow. Run commands manually.
- name: installed Mercurial
  command: /usr/bin/yum install -y patch /var/tmp/mercurial-3.4.1-0.x86_64.rpm
