---

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download Mercurial package (CentOS 6)
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS6/mercurial-3.8.4-1.x86_64.rpm
           dest=/var/tmp/mercurial-3.8.4-1.x86_64.rpm
           sha256sum=2a4654b1a8e5d47fc6a96c826210d057dcc78523de72f70d266e5fc5f5685c90
  when: ansible_distribution_major_version == '6'

- name: download Mercurial package (CentOS 7)
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS7/mercurial-3.8.4-1.x86_64.rpm
           dest=/var/tmp/mercurial-3.8.4-1.x86_64.rpm
           sha256sum=22850355ed4949906e922920651375af342b4ad7a6535cc5ce2ed088d91add01
  when: ansible_distribution_major_version == '7'

- name: Install patch package
  yum: name=patch state=present

# The yum module is slow. Run commands manually.
- name: installed Mercurial
  command: /usr/bin/yum localinstall -y /var/tmp/mercurial-3.8.4-1.x86_64.rpm
