---
- name: install packages required by autoland
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - gcc
    - openssh-clients
    - postgresql
    - python-devel
    - python-pip
    - libffi
    - libffi-devel
    - libpqxx-devel
    - openssl-devel
    - httpd
    - mod_wsgi
    - mod_ssl
    - ca-certificates

- name: download Mozilla rpms
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS7/{{ item.path }}
           dest=/var/tmp/{{ item.path }}
           sha256sum={{ item.sha256 }}
  with_items:
    - { path: mercurial-4.0.1-1.x86_64.rpm, sha256: 4ed004977d5447351dea0a0cf1229dc2c25a944971a04fd6a4d9ca56e0ff20c0 }

- name: install Mozilla rpms
  command: yum localinstall -y /var/tmp/mercurial-4.0.1-1.x86_64.rpm

