---
# In order for this to be idempotent we must determine if /repos is mounted
- name: determine if mounted
  command: mountpoint -q /repos
  register: mount_stat
  failed_when: False
  changed_when: False

# - debug: var=mount_stat

- name: format drive
  command: mkfs.ext4 /dev/xvdb
  when: mount_stat.rc != 0

- name: create mount point
  file: path=/repos
        state=directory
  when: mount_stat.rc != 0

- name: mount drive
  mount: name=/repos src=/dev/xvdb fstype=ext4 state=mounted
  when: mount_stat.rc != 0

- name: set ownership of repos
  file: path=/repos
        mode=0755

