---
- name: Create Review Board user
  user: name=reviewboard

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download Mercurial package
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS6/mercurial-3.4.1-0.x86_64.rpm
           dest=/var/tmp/mercurial-3.4.1-0.x86_64.rpm
           sha256sum=4e6190232ae217aacc894c0baf8e61900cb55d4ee0406a09a22b70cb9c6dfbd0

# The yum module is slow. Run commands manually.
- name: System packages installed
  command: /usr/bin/yum install -y memcached mod_wsgi patch /var/tmp/mercurial-3.4.1-0.x86_64.rpm

# The kill-wsgi-procs support script requires psutil, which isn't part of
# the MozReview virtualenv. Install it as a one-off
- name: install psutil
  pip: virtualenv=/venv
       name=psutil
       version=2.2.1

- name: Synchronize version-control-tools
  synchronize: src={{ vct }}/ dest=/version-control-tools/ recursive=yes delete=yes

- name: Install python libraries
  command: /venv/bin/python setup.py develop chdir=/version-control-tools/pylib/{{ item }}
  with_items:
    - mozautomation
    - mozreview
    - rbbz
    - rbmotd

- name: Remove default httpd configs
  file: path={{ item }} state=absent
  with_items:
    - /etc/httpd/conf.d/welcome.conf
    - /etc/httpd/conf.d/README

- name: Install httpd vhost config
  copy: src=vhost.conf dest=/etc/httpd/conf.d/reviewboard.conf

- name: Install Review Board
  command: /venv/bin/rb-site install --noinput --opt-out-support-data --domain-name=example.com --admin-user=admin+1 --admin-password=password --admin-email=admin@example.com --db-type=sqlite3 --db-name=/reviewboard/data/reviewboard.db --cache-type=memcached --cache-info=localhost:11211 --web-server-type=apache --python-loader=wsgi /reviewboard creates=/reviewboard

- name: Install Review Board installation script
  copy: src=install-reviewboard dest=/install-reviewboard owner=reviewboard group=reviewboard mode=0755

- name: Configure Review Board
  command: /install-reviewboard

- name: Install support scripts
  copy: src={{ item }} dest=/{{ item }} owner=reviewboard group=reviewboard mode=0755
  with_items:
    - create-local-user
    - dump-profile
    - grant-permission
    - kill-wsgi-procs
    - make-admin
    - refresh
    - set-site-url

- name: Install entrypoint script
  copy: src=entrypoint.py dest=/entrypoint.py owner=root mode=0755

- name: Install container run script
  copy: src=run dest=/run owner=root mode=0755
