# Installs CRON to periodically generate Mercurial bundles for popular
# repositories.
---

- name: ensure bundles directory exists
  file: path=/repo/bundles owner=hg group=hg state=directory mode=0775

# TODO enable once Ansible 2.0 is released.
#- name: send CRON mail to developer-services list
#  cronvar: user=hg name=MAILTO value=developer-services@mozilla.org

- name: create CRON to generate S3 bundles
  cron: name="Generate Mercurial bundles for {{ item.repo }}"
        user=hg
        job='/repo/hg/scripts/outputif /repo/hg/venv_tools/bin/python /repo/hg/scripts/generate-hg-s3-bundles {{ item.repo }}'
        day=*
        month=*
        minute={{ item.minute }}
        hour={{ item.hour }}
  with_items:
    # Schedule for when the sun is over the Pacific Ocean, as this is
    # when the fewest pushes occur. Also, hgssh1 is on PDT not UTC.
    - { hour: 21, minute: 0, repo: mozilla-central }
    - { hour: 21, minute: 30, repo: integration/fx-team }
    - { hour: 22, minute: 0, repo: integration/mozilla-inbound }
    - { hour: 22, minute: 30, repo: integration/b2g-inbound }
    - { hour: 23, minute: 0, repo: integration/gaia-central }
    - { hour: 23, minute: 30, repo: releases/mozilla-release }
    - { hour: 0, minute: 0, repo: releases/mozilla-aurora }
    - { hour: 0, minute: 30, repo: releases/mozilla-beta }
    - { hour: 1, minute: 0, repo: releases/mozilla-esr38 }
    - { hour: 1, minute: 30, repo: build/tools }
    - { hour: 1, minute: 30, repo: build/mozharness }
    - { hour: 1, minute: 45, repo: build/talos }
    - { hour: 2, minute: 0, repo: comm-central }
    - { hour: 2, minute: 30, repo: projects/ash }
    - { hour: 3, minute: 0, repo: projects/holly }
    - { hour: 3, minute: 30, repo: projects/jamun }
    - { hour: 4, minute: 0, repo: projects/larch }
    - { hour: 4, minute: 30, repo: projects/oak }
    - { hour: 5, minute: 0, repo: projects/cedar }
    - { hour: 5, minute: 30, repo: releases/mozilla-b2g34_v2_1 }
    - { hour: 6, minute: 30, repo: releases/mozilla-b2g37_v2_2 }
    - { hour: 7, minute: 0, repo: releases/mozilla-b2g37_v2_2r }
    - { hour: 7, minute: 30, repo: releases/mozilla-b2g32_v2_0 }
    - { hour: 8, minute: 0, repo: releases/mozilla-b2g32_v2_0m }
    - { hour: 8, minute: 30, repo: releases/mozilla-esr31 }
