---
- name: hg directories exist
  file: path=/repo/hg/{{ item }}
        owner=hg
        group=hg
        mode=0755
        state=directory
  with_items:
    - extensions/bundleclone
    - extensions/pushlog
    - extensions/serverlog
    - scripts

- name: install support scripts
  copy: src={{ vct | mandatory }}/scripts/{{ item }}
        dest=/repo/hg/scripts/{{ item }}
        mode=0755
  with_items:
    - aggregate-s3-bucket-logs
    - generate-hg-s3-bundles
    - outputif

- name: install pushlog extension
  copy: src={{ vct }}/hgext/pushlog/__init__.py
        dest=/repo/hg/extensions/pushlog/__init__.py
        owner=hg
        group=hg
        mode=0644

- name: install bundleclone extension
  copy: src={{ vct }}/hgext/bundleclone/__init__.py
        dest=/repo/hg/extensions/bundleclone/__init__.py
        owner=hg
        group=hg
        mode=0644

- name: install pushrebase extension
  copy: src={{ vct }}/hgext/pushrebase/__init__.py
        dest=/repo/hg/extensions/pushrebase.py
        owner=hg
        group=hg
        mode=0644

- name: install serverlog extension
  copy: src={{ vct }}/hgext/serverlog/__init__.py
        dest=/repo/hg/extensions/serverlog/__init__.py
        owner=hg
        group=hg
        mode=0644
