---
- name: hg directories exist
  file: path=/repo/hg/{{ item }} owner=hg group=hg mode=0755 state=directory
  with_items:
    - extensions
    - extensions/parsedatetime
    - extensions/pushlog
    - extensions/serverlog
    - hg_templates
    - libraries
    - libraries/mozhghooks
    - webroot_wsgi

- name: install pushlog hgweb files
  copy: src={{ vct | mandatory }}/hgext/pushlog-legacy/{{ item }} dest=/repo/hg/extensions/{{ item }} owner=hg group=hg mode=0644
  with_items:
    - buglink.py
    - feedparser.py
    - hgwebjson.py
    - pushlog-feed.py
    - parsedatetime/__init__.py
    - parsedatetime/parsedatetime.py
    - parsedatetime/parsedatetime_consts.py

- name: install pushlog extension
  copy: src={{ vct }}/hgext/pushlog/__init__.py dest=/repo/hg/extensions/pushlog/__init__.py owner=hg group=hg mode=0644

- name: install serverlog extension
  copy: src={{ vct }}/hgext/serverlog/__init__.py dest=/repo/hg/extensions/serverlog/__init__.py owner=hg group=hg mode=0644

- name: install hooks
  copy: src={{ vct }}/hghooks/mozhghooks/{{ item }} dest=/repo/hg/libraries/mozhghooks/{{ item }} owner=hg group=hg mode=0644
  with_items:
    - changelog_correctness.py
    - commit-message.py
    - prevent_case_only_renames.py
    - prevent_idl_change_without_uuid_bump.py
    - prevent_string_changes.py
    - prevent_uuid_changes.py
    - prevent_webidl_changes.py
    - push_printurls.py
    - single_head_per_branch.py
    - treeclosure.py
    - treeclosure_comm_central.py
    - try_mandatory.py
    - whitelist_qa.py
    - whitelist_releng.py

- name: synchronize hg templates
  synchronize: src={{ vct }}/hgtemplates/ dest=/repo/hg/hg_templates/ recursive=yes delete=yes

- name: adjust file permissions for hg templates
  command: /bin/chown -R hg:hg /repo/hg/hg_templates
