---
- name: hg directories exist
  file: path=/repo/hg/{{ item }}
        owner=hg
        group=hg
        mode=0755
        state=directory
  with_items:
    - scripts

- name: install support scripts
  copy: src={{ vct | mandatory }}/scripts/{{ item }}
        dest=/repo/hg/scripts/{{ item }}
        mode=0755
  with_items:
    - aggregate-s3-bucket-logs
    - generate-hg-s3-bundles
    - outputif
