---
- name: prepare v-c-t repo
  hg: repo={{ repo }} dest={{ vct }} revision={{ rev }} force=yes purge=yes executable={{ venv }}/bin/hg

- name: build MozReview eggs
  command: "{{ python }} setup.py bdist_egg chdir={{ vct }}/{{ item }}"
  with_items:
    - pylib/mozreview
    - pylib/rbbz

- name: Install Review Board extension eggs
  shell: "{{ easy_install }} -U dist/*.egg chdir={{ vct }}/{{ item }}"
  with_items:
    - pylib/mozreview
    - pylib/rbbz

- name: Generate static Review Board files
  command: "{{ rbsite }} manage {{ sitehome }} -- collectstatic --noinput"
