---
- name: prepare reviewboard-fork repo
  hg: repo={{ rb_repo }}
      dest={{ rb_vct }}/reviewboard-fork
      revision={{ rb_rev }}
      force=yes
      purge=yes
      executable={{ venv }}/bin/hg

# The hg module's purge doesn't delete ignored files. Boo. Force that
# because old files may cause chaos.
- name: delete ignored files from reviewboard-fork repo
  command: "{{ venv }}/bin/hg --config extensions.purge= -R {{ rb_vct }}/reviewboard-fork purge --all"

- name: install djblets fork
  command: "{{ python }} setup.py install chdir={{ rb_vct }}/reviewboard-fork/djblets"

- name: install reviewboard fork
  command: "{{ python }} setup.py install chdir={{ rb_vct }}/reviewboard-fork/reviewboard"

- name: prepare v-c-t repo
  hg: repo={{ repo }}
      dest={{ rb_vct }}
      revision={{ rev }}
      force=yes
      purge=yes
      executable={{ venv }}/bin/hg

# Delete ignored filed to avoid chaos.
- name: delete ignored files from version-control-tools repo
  command: "{{ venv }}/bin/hg --config extensions.purge= -R {{ rb_vct }} purge --all"

# mozreview imports from mozautomation package. So, we need to install
# mozautomation before mozreview can be built.

- name: install mozautomation egg
  command: "{{ venv }}/bin/pip install --upgrade --no-deps --force-reinstall {{ rb_vct }}/pylib/mozautomation"

# rbbz imports from mozreview package. So, we need to install mozreview before
# rbbz can be built.

- name: build mozreview egg
  command: "{{ python }} setup.py bdist_egg chdir={{ rb_vct }}/pylib/mozreview"

- name: install mozreview egg
  shell: "{{ easy_install }} -U dist/*.egg chdir={{ rb_vct }}/pylib/mozreview"

- name: build rbbz egg
  command: "{{ python }} setup.py bdist_egg chdir={{ rb_vct }}/pylib/rbbz"

- name: install rbbz egg
  shell: "{{ easy_install }} -U dist/*.egg chdir={{ rb_vct }}/pylib/rbbz"

- name: build rbmotd egg
  command: "{{ python }} setup.py bdist_egg chdir={{ rb_vct }}/pylib/rbmotd"

- name: install rbmotd egg
  shell: "{{ easy_install }} -U dist/*.egg chdir={{ rb_vct }}/pylib/rbmotd"

- name: build pygments_override egg
  command: "{{ python }} setup.py bdist_egg chdir={{ rb_vct }}/pylib/pygments_override"

- name: install pygments_override egg
  shell: "{{ easy_install }} -U dist/*.egg chdir={{ rb_vct }}/pylib/pygments_override"

- name: Generate static Review Board files from extensions
  command: "{{ rbsite }} manage {{ sitehome }} -- install-extension-media --force"

- name: Generate static Review Board files
  command: "{{ rbsite }} manage {{ sitehome }} -- collectstatic --noinput"
