---

- name: download python packaging tools
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/{{ item.path }}
           dest=/var/tmp/{{ item.path }}
           sha256sum={{ item.shasum }}
  with_items:
    - { path: get-pip-8.0.3.py, shasum: 85a499fbd52603045812df8ca1c0491483e5f28eca15a3b3025507a66f225acf }
    - { path: virtualenv-14.0.6.tar.gz, shasum: 1ffb6a02d8999e9c97ad8f04b1d2ba44421dfb8f8a98b54aea5c6fdfb53bc526 }

- name: extract virtualenv package
  unarchive: src=/var/tmp/virtualenv-14.0.6.tar.gz
             dest=/var/tmp
             copy=no

- name: install latest packaging wheels to virtualenv package
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/{{ item.path }}
           dest=/var/tmp/virtualenv-14.0.6/virtualenv_support/{{ item.path }}
           sha256sum={{ item.shasum }}
  with_items:
    - { path: pip-8.0.3-py2.py3-none-any.whl, shasum: b0335bc837f9edb5aad03bd43d0973b084a1cbe616f8188dc23ba13234dbd552 }
    - { path: setuptools-20.1.1-py2.py3-none-any.whl, shasum: dfdbc643f8900d9e617e48a42ae389aa18fd6fbd2846f24f2a4678b8d9412acb }

- name: create virtualenv in {{ venv }}
  command: /usr/bin/python2.7 /var/tmp/virtualenv-14.0.6/virtualenv.py {{ venv }} creates={{ venv }}

# If the virtualenv is fresh, Python packaging packages should be up to date.
# But if the virtualenv is left over from a previous install, the packaging
# files may be out of date. We install the newest packaging packages via
# get-pip.py, which is a self-contained version of `pip install`. We can't
# blindly use {{ venv }}/bin/pip because it may not support wheels!
- name: upgrade python packaging packages
  command: "{{ venv }}/bin/python /var/tmp/get-pip-8.0.3.py --upgrade --no-index --find-links /var/tmp/virtualenv-14.0.6/virtualenv_support pip setuptools wheel"

- name: copy requirements.txt
  copy: src={{ requirements }}
        dest={{ venv }}/requirements.txt
        mode=0644

- name: populate virtualenv {{ venv }}
  command: "{{ venv }}/bin/pip install --require-hashes -r {{ venv }}/requirements.txt"
