---
dependencies:
  - supervisor
  - { role: hg-web,
      mirror_source: "@mirror_source@",
      mirror_ssh_user: hg,
      wsgi_processes: 4,
      httpd_start_servers: 1,
      httpd_min_spare_servers: 1,
      httpd_max_spare_servers: 2,
      httpd_server_limit: 4,
      httpd_max_clients: 4,
      vct_node: "DOCKER",
    }
