---
- name: determine if running in Docker
  stat: path=/vct
  register: vct_dir

- include: ../../../tasks/systemd-mail-unit-output.yml
  when: vct_dir.stat.exists == False

- name: Install packages required to run a Mercurial server
  yum: name={{ item }} state=present
  with_items:
    - sudo
    - tar

- name: install global ssh config
  copy: src=ssh_config
        dest=/etc/ssh/ssh_config
        owner=root
        group=root
        mode=0640

- name: Create groups for hg services
  group: name={{ item.name }} gid={{ item.gid }}
  with_items:
    - { name: 'hg-aggregate', gid: 5601 }
    - { name: 'hg-notifier', gid: 5603 }

- name: create users for hg services
  user: name={{ item.name }}
        group={{ item.name }}
        uid={{ item.uid }}
  with_items:
    - { name: 'hg-aggregate', uid: 5601 }
    - { name: 'hg-notifier', uid: 5603 }

- name: install hg-master.target systemd unit
  copy: src=hg-master.target
        dest=/etc/systemd/system/hg-master.target
        owner=root
        group=root
        mode=0644
  notify: systemd daemon reload
  when: vct_dir.stat.exists == False

- name: enable hg-master.target systemd unit
  service: name=hg-master.target
           enabled=yes
  when: vct_dir.stat.exists == False

- name: hg user ssh config is prepared
  file: path=/home/hg/.ssh state=directory mode=0775 owner=hg group=hg

- name: install pash configuration file
  template: src=pash.json.j2
            dest=/etc/mercurial/pash.json
            owner=root
            group=root
            mode=0644

- name: replication SSH key is present
  command: /usr/bin/ssh-keygen -b 4096 -f /etc/mercurial/mirror -t rsa -N '' creates=/etc/mercurial/mirror

- name: capture content of replication SSH key
  slurp: src=/etc/mercurial/mirror.pub
  register: mirror_ssh_key_public

- name: ensure proper permissions on replication key
  file: path={{ item }} owner=hg group=hg
  with_items:
    - /etc/mercurial/mirror
    - /etc/mercurial/mirror.pub

- name: hg user has replication key configured in authorized_keys
  copy: dest=/home/hg/.ssh/authorized_keys
        content="{{ mirror_ssh_key_public.content | b64decode }}"
        owner=hg
        group=hg
        mode=0640

- name: known hosts file for mirrors is populated
  template: src=known_hosts.j2
            dest=/etc/mercurial/known_hosts
            owner=hg
            group=hg
            mode=0660

- name: list of mirrors file is populated
  template: src=mirrors.j2
            dest=/etc/mercurial/mirrors
            owner=root
            group=root
            mode=0644

- name: User repository directories are present
  file: path=/repo/hg/mozilla/users state=directory mode=0775 owner=hg group=scm_level_1

- name: create virtualenv for tools
  include: ../../../tasks/virtualenv.yml
           venv=/var/hg/venv_tools
           requirements=../roles/hg-ssh/files/requirements-tools.txt

# Hooks are referenced in various hgrc files via "python:mozhghooks.*".
# This means they are imported as Python modules from the "mozhghooks"
# package. We create a .pth file telling the virtualenv that
# all hooks are located in the version-control-tools checkout.
#
# The vcsreplicator Python package contains support code for managing
# replication. Also add it to the virtualenv.
- name: add packages to virtualenvs
  copy: dest=/var/hg/{{ item.venv }}/lib/python2.7/site-packages/{{ item.pth }}.pth
        content=/var/hg/version-control-tools/{{ item.path }}
        owner=root
        group=root
        mode=0644
  with_items:
    - { venv: venv_pash, path: hghooks, pth: mozhghooks }
    - { venv: venv_tools, path: hghooks, pth: mozhghooks }
    - { venv: venv_pash, path: pylib/vcsreplicator, pth: vcsreplicator }
    - { venv: venv_tools, path: pylib/vcsreplicator, pth: vcsreplicator }

- name: determine if v-c-t clone is present
  stat: path=/var/hg/version-control-tools/.hg
  register: vct_clone

- name: create v-c-t clone (server only)
  command: /var/hg/venv_tools/bin/hg --config extensions.vcsreplicator=! clone https://hg.mozilla.org/hgcustom/version-control-tools /var/hg/version-control-tools
  when: vct_dir.stat.exists == False and vct_clone.stat.exists == False

- name: pull version-control-tools repo (server only)
  command: /var/hg/venv_tools/bin/hg --config extensions.vcsreplicator=! -R /var/hg/version-control-tools pull https://hg.mozilla.org/hgcustom/version-control-tools
  when: vct_dir.stat.exists == False

- name: update version-control-tools repo (server only)
  command: /var/hg/venv_tools/bin/hg -R /var/hg/version-control-tools up -r {{ lookup('file', '../../../../.vctnode') }}
  when: vct_dir.stat.exists == False

- name: delete ignored files from version-control-tools repo
  command: /var/hg/venv_tools/bin/hg --config extensions.purge= -R /var/hg/version-control-tools purge --all
  when: vct_dir.stat.exists == False

- name: rsync version-control-tools repo (Docker only)
  command: /usr/bin/rsync -a --delete-after /vct/ /var/hg/version-control-tools/
  when: vct_dir.stat.exists == True

- name: ensure version-control-tools permissions are sane (Docker only)
  command: /bin/chmod -R a+r /var/hg/version-control-tools
  when: vct_dir.stat.exists == True

- name: install vcsreplicator into virtualenv
  command: /var/hg/venv_tools/bin/pip install --upgrade --no-deps --force-reinstall /var/hg/version-control-tools/pylib/vcsreplicator

- name: install rsyslog policy for hg
  copy: src=rsyslog-hg.conf
        dest=/etc/rsyslog.d/hg-master.conf
         owner=root
         group=root
         mode=0644
  notify: restart rsyslogd

- name: install logrotate config for hg
  copy: src=logrotate-hg.conf
        dest=/etc/logrotate.d/hg-master
        owner=root
        group=root
        mode=0644

- name: sudoers policy for repo-push is in place
  copy: src=repo-push.sudoers dest=/etc/sudoers.d/repo-push

- name: global Mercurial configs are in place
  template: src={{ item }}.j2
            dest=/etc/mercurial/{{ item }}
            mode=0664
            owner=root
            group=root
  with_items:
    - hgrc
    - notifications.ini
    - pushdataaggregator.ini

- name: install repo-push script
  copy: src={{ vct }}/scripts/repo-push.sh
        dest=/usr/local/bin/repo-push.sh
        owner=root
        group=root
        mode=0755

- name: ensure bundles directory exists
  file: path=/repo/hg/bundles
        state=directory
        owner=hg
        group=hg
        mode=0775

- name: write list of repositories to generate bundles for
  copy: src=bundle-repos
        dest=/repo/hg/bundles/repos
        owner=hg
        group=hg
        mode=0644

- name: install repo unify config files
  copy: src={{ item }}
        dest=/etc/mercurial/{{ item }}
        owner=root
        group=root
        mode=0644
  with_items:
    - unify-mozilla-central-gd.ini
    - unify-mozilla-unified.ini

- name: sysconfig file for unify repo daemon
  copy: src=sysconfig-unifyrepo
        dest=/etc/sysconfig/unifyrepo
        owner=root
        group=root
        mode=0644

# Ideally, we would have separate override files for each service. But
# it doesn't appear systemd allows there to be a generic e.g.
# mail-unit-output@.service and an instance e.g.
# mail-unit-output@hg-bundle-generate.service.d

- name: create directory mail-unit-output override file
  file: path=/etc/systemd/system/mail-unit-output@.service.d
        state=directory
        owner=root
        group=root
        mode=0755

- name: install mail-unit-output override
  copy: src=mail-unit-output-override.conf
        dest=/etc/systemd/system/mail-unit-output@.service.d/override.conf
        owner=root
        group=root
        mode=0644
  notify: systemd daemon reload
  when: vct_dir.stat.exists == False

- name: create directory for Nagios files
  file: path={{ item }}
        state=directory
        owner=root
        group=root
        mode=0755
  with_items:
    - /etc/nagios/nrpe.d
    - /usr/lib64/nagios/plugins/custom

- name: install Nagios check for hg writing into kafka
  copy: src=check_kafka_hg_heartbeat
        dest=/usr/lib64/nagios/plugins/custom/check_kafka_hg_heartbeat
        owner=root
        group=root
        mode=0755

- name: install NRPE check configs
  copy: src={{ item }}
        dest=/etc/nagios/nrpe.d/{{ item }}
        owner=root
        group=root
        mode=0644
  with_items:
    - check_kafka_hg_heartbeat.cfg
    - check_pulsenotifier_lag.cfg
    - check_pushdataaggregator_lag.cfg
    - check_snsnotifier_lag.cfg
  notify: restart nrpe.service

- name: install systemd unit files
  copy: src={{ item }}
        dest=/etc/systemd/system/{{ item }}
        owner=root
        group=root
        mode=0644
  notify: systemd daemon reload
  when: vct_dir.stat.exists == False
  with_items:
    - hg-bundle-generate.service
    - hg-bundle-generate.timer
    - pulsenotifier.service
    - pushdataaggregator.service
    - snsnotifier.service
    - unifyrepo.service
    - hg-master-monitor.service
    - hg-master-monitor.timer

- name: systemd services are enabled (server only)
  service: name={{ item }}
           enabled=yes
  when: vct_dir.stat.exists == False
  with_items:
    - hg-bundle-generate.timer
    - pulsenotifier.service
    - pushdataaggregator.service
    - snsnotifier.service
    - unifyrepo.service
    - hg-master-monitor.timer

- name: ensure hg-master-monitor.timer is started (server only)
  service: name=hg-master-monitor.timer
           state=started
  when: vct_dir.stat.exists == False

- name: restart all services specific to master server (server only)
  service: name=hg-master.target
           state=restarted
  ignore_errors: True
  when: vct_dir.stat.exists == False
