---
# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download Mercurial package
  get_url: url=https://people.mozilla.org/~gszorc/mercurial-3.4.1-0.x86_64.rpm
           dest=/var/tmp/mercurial-3.4.1-0.x86_64.rpm
           sha256sum=4e6190232ae217aacc894c0baf8e61900cb55d4ee0406a09a22b70cb9c6dfbd0

- name: Install packages required to run a Mercurial server
  yum: name={{ item }} state=present
  with_items:
    - python27
    - python-ldap
    - sudo
    - rsyslog
    - tar
    - /var/tmp/mercurial-3.4.1-0.x86_64.rpm

- name: Create groups for SCM ACLs
  group: name={{ item.name }} gid={{ item.gid }}
  with_items:
    - { name: 'scm_level_1', gid: 673 }
    - { name: 'scm_level_2', gid: 685 }
    - { name: 'scm_level_3', gid: 679 }
    - { name: 'scm_l10n', gid: 678 }
    - { name: 'scm_l10n_infra', gid: 680 }
    - { name: 'scm_sec_sensitive', gid: 686 }
    - { name: 'scm_ecmascript', gid: 687 }

- name: Create hg group
  group: name=hg

- name: Create hg user
  user: name=hg group=hg

- name: hg user ssh config is prepared
  file: path=/home/hg/.ssh state=directory mode=0775 owner=hg group=hg

- name: Mercurial config directory is present
  file: path=/etc/mercurial state=directory mode=0775

- name: directories for support tools is present
  file: path=/usr/local/bin
        state=directory
        owner=root
        group=root
        mode=0755

- name: replication SSH key is present
  command: /usr/bin/ssh-keygen -b 2048 -f /etc/mercurial/mirror -t rsa creates=/etc/mercurial/mirror

- name: capture content of replication SSH key
  slurp: src=/etc/mercurial/mirror.pub
  register: mirror_ssh_key_public

- name: ensure proper permissions on replication key
  file: path={{ item }} owner=hg group=hg
  with_items:
    - /etc/mercurial/mirror
    - /etc/mercurial/mirror.pub

- name: hg user has replication key configured in authorized_keys
  copy: dest=/home/hg/.ssh/authorized_keys
        content={{ mirror_ssh_key_public.content | b64decode }}
        owner=hg
        group=hg
        mode=0640

- name: Mercurial known hosts file is present
  file: path=/etc/mercurial/known_hosts mode=0660 owner=hg group=hg state=touch

- name: Mercurial repository directories are present
  file: path={{ item }} state=directory mode=0775
  with_items:
    - /repo/hg/mozilla
    - /repo/hg/extensions
    - /repo/hg/scripts

- name: User repository directories are present
  file: path=/repo/hg/mozilla/users state=directory mode=0775 owner=hg group=scm_level_1

- name: Mercurial log files are present and writable
  file: path={{ item }} mode=0666 state=touch
  with_items:
    - /var/log/hg-push.log
    - /var/log/pash.log

- name: sudoers policy for repo-push is in place
  copy: src=repo-push.sudoers dest=/etc/sudoers.d/repo-push

- name: Global Mercurial config is in place
  copy: src=hgrc dest=/etc/mercurial/hgrc mode=0664 owner=root group=root

# pash is a collection of Python files handling SSH connections. They behave
# like a Python module but are installed not as such for historical reasons.
- name: install pash
  copy: src={{ vct }}/scripts/pash/{{ item }}
        dest=/usr/local/bin/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
    - hg_helper.py
    - ldap_helper.py
    - pash.py
    - repo_group.py
    - sh_helper.py

- name: install repo-push script
  copy: src={{ vct }}/scripts/repo-push.sh
        dest=/usr/local/bin/repo-push.sh
        owner=root
        group=root
        mode=0755

- name: install push scripts
  copy: src={{ vct }}/scripts/{{ item }}
        dest=/repo/hg/scripts/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
    - push-repo.sh
    - record-pushes.sh

