---
- name: determine if running in Docker
  stat: path=/vct
  register: vct_dir

- name: Install packages required to run a Mercurial server
  yum: name={{ item }} state=present
  with_items:
    # Needed to build python-ldap package for virtualenv.
    - openldap-devel
    - python27
    - python27-devel
    - python-ldap
    - sudo
    - rsyslog
    - tar

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download Mozilla rpms
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS6/{{ item.path }}
           dest=/var/tmp/{{ item.path }}
           sha256sum={{ item.sha256 }}
  with_items:
    - { path: mercurial-3.7.3-1.x86_64.rpm, sha256: 924a8828cfe53901db1366115d927b958f35f5e6a9c418cbc670c5e19137c090 }

- name: install Mozilla rpms
  command: yum localinstall -y /var/tmp/mercurial-3.7.3-1.x86_64.rpm

- name: install global ssh config
  copy: src=ssh_config
        dest=/etc/ssh/ssh_config
        owner=root
        group=root
        mode=0640

- name: Create groups for SCM ACLs
  group: name={{ item.name }} gid={{ item.gid }}
  with_items:
    - { name: 'scm_level_1', gid: 673 }
    - { name: 'scm_level_2', gid: 685 }
    - { name: 'scm_level_3', gid: 679 }
    - { name: 'scm_l10n', gid: 678 }
    - { name: 'scm_l10n_infra', gid: 680 }
    - { name: 'scm_sec_sensitive', gid: 686 }
    - { name: 'scm_ecmascript', gid: 687 }

- name: Create hg group
  group: name=hg

- name: Create hg user
  user: name=hg group=hg

- name: hg user ssh config is prepared
  file: path=/home/hg/.ssh state=directory mode=0775 owner=hg group=hg

- name: Mercurial config directory is present
  file: path=/etc/mercurial state=directory mode=0775

- name: directories for support tools is present
  file: path=/usr/local/bin
        state=directory
        owner=root
        group=root
        mode=0755

- name: install pash configuration file
  template: src=pash.json.j2
            dest=/etc/mercurial/pash.json
            owner=root
            group=root
            mode=0644

- name: replication SSH key is present
  command: /usr/bin/ssh-keygen -b 2048 -f /etc/mercurial/mirror -t rsa creates=/etc/mercurial/mirror

- name: capture content of replication SSH key
  slurp: src=/etc/mercurial/mirror.pub
  register: mirror_ssh_key_public

- name: ensure proper permissions on replication key
  file: path={{ item }} owner=hg group=hg
  with_items:
    - /etc/mercurial/mirror
    - /etc/mercurial/mirror.pub

- name: hg user has replication key configured in authorized_keys
  copy: dest=/home/hg/.ssh/authorized_keys
        content={{ mirror_ssh_key_public.content | b64decode }}
        owner=hg
        group=hg
        mode=0640

- name: known hosts file for mirrors is populated
  template: src=known_hosts.j2
            dest=/etc/mercurial/known_hosts
            owner=hg
            group=hg
            mode=0660

- name: Mercurial repository directories are present
  file: path={{ item }} state=directory mode=0775
  with_items:
    - /repo/hg/mozilla
    - /repo/hg/extensions
    - /repo/hg/scripts
    - /var/hg

- name: User repository directories are present
  file: path=/repo/hg/mozilla/users state=directory mode=0775 owner=hg group=scm_level_1

- name: create virtualenv for pash
  include: ../../../tasks/virtualenv.yml
           venv=/repo/hg/venv_pash
           requirements=../roles/hg-ssh/files/requirements-pash.txt

- name: create virtualenv for tools
  include: ../../../tasks/virtualenv.yml
           venv=/repo/hg/venv_tools
           requirements=../roles/hg-ssh/files/requirements-tools.txt


# Hooks are referenced in various hgrc files via "python:mozhghooks.*".
# This means they are imported as Python modules from the "mozhghooks"
# package. We create a .pth file telling the virtualenv that
# all hooks are located in the version-control-tools checkout.
#
# The vcsreplicator Python package contains support code for managing
# replication. Also add it to the virtualenv.
- name: add packages to virtualenvs
  copy: dest=/repo/hg/{{ item.venv }}/lib/python2.7/site-packages/{{ item.pth }}.pth
        content=/repo/hg/version-control-tools/{{ item.path }}
        owner=root
        group=root
        mode=0644
  with_items:
    - { venv: venv_pash, path: hghooks, pth: mozhghooks }
    - { venv: venv_tools, path: hghooks, pth: mozhghooks }
    - { venv: venv_pash, path: pylib/vcsreplicator, pth: vcsreplicator }
    - { venv: venv_tools, path: pylib/vcsreplicator, pth: vcsreplicator }

- name: set up version-control-tools repo (server only)
  command: /repo/hg/venv_tools/bin/hg --config extensions.vcsreplicator=! -R /repo/hg/version-control-tools pull https://hg.mozilla.org/hgcustom/version-control-tools
  when: vct_dir.stat.exists == False

- name: update version-control-tools repo (server only)
  command: /repo/hg/venv_tools/bin/hg -R /repo/hg/version-control-tools up -r {{ lookup('file', '../../../../.vctnode') }}
  when: vct_dir.stat.exists == False

- name: delete ignored files from version-control-tools repo
  command: /repo/hg/venv_tools/bin/hg --config extensions.purge= -R /repo/hg/version-control-tools purge --all
  when: vct_dir.stat.exists == False

- name: rsync version-control-tools repo (Docker only)
  command: /usr/bin/rsync -a --delete-after /vct/ /repo/hg/version-control-tools/
  when: vct_dir.stat.exists == True

- name: ensure version-control-tools permissions are sane (Docker only)
  command: /bin/chmod -R a+r /repo/hg/version-control-tools
  when: vct_dir.stat.exists == True

- name: install rsyslog policy for hg
  copy: src=rsyslog-hg.conf
        dest=/etc/rsyslog.d/hg.conf
        owner=root
        group=root
        mode=0644
  notify: restart rsyslogd

- name: install logrotate config for hg
  copy: src=logrotate-hg.conf
        dest=/etc/logrotate.d/hg
        owner=root
        group=root
        mode=0644

- name: Mercurial log files are present and writable
  file: path={{ item }} mode=0666 state=touch
  with_items:
    - /var/log/hg-push.log
    - /var/log/pash.log

- name: sudoers policy for repo-push is in place
  copy: src=repo-push.sudoers dest=/etc/sudoers.d/repo-push

- name: global Mercurial config is in place
  template: src=hgrc.j2
            dest=/etc/mercurial/hgrc
            mode=0664
            owner=root
            group=root

# pash is a collection of Python files handling SSH connections. They behave
# like a Python module but are installed not as such for historical reasons.
- name: install pash
  copy: src={{ vct }}/hgserver/pash/{{ item }}
        dest=/usr/local/bin/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
    # Install pash.py first to ensure SSH root login works.
    - pash.py
    - hg_helper.py
    - ldap_helper.py
    - pash_wrapper
    - repo_group.py
    - sh_helper.py

- name: install repo-push script
  copy: src={{ vct }}/scripts/repo-push.sh
        dest=/usr/local/bin/repo-push.sh
        owner=root
        group=root
        mode=0755

- name: install push scripts
  copy: src={{ vct }}/scripts/{{ item }}
        dest=/repo/hg/scripts/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
    - push-repo.sh
    - record-pushes.sh

- name: ensure bundles directory exists
  file: path=/repo/bundles
        state=directory
        owner=hg
        group=hg
        mode=0775

- name: write list of repositories to generate bundles for
  copy: src=bundle-repos
        dest=/repo/bundles/repos
        owner=hg
        group=hg
        mode=0644

- name: create directory for Nagios files
  file: path={{ item }}
        state=directory
        owner=root
        group=root
        mode=0755
  with_items:
    - /etc/nagios/nrpe.d
    - /usr/lib64/nagios/plugins/custom

- name: install Nagios check for hg writing into kafka
  copy: src=check_kafka_hg_heartbeat
        dest=/usr/lib64/nagios/plugins/custom/check_kafka_hg_heartbeat
        owner=root
        group=root
        mode=0755

- name: install NRPE check config
  copy: src=check_kafka_hg_heartbeat.cfg
        dest=/etc/nagios/nrpe.d/check_kafka_hg_heartbeat.cfg
        owner=root
        group=root
        mode=0644

# Pull in tasks shared between hg-ssh and hg-web.
# This should run last to ensure all preconditions are met.
- include: ../../../tasks/hgmo-extensions.yml
