# This playbook is used to update the production deployment of
# MozReview (reviewboard.mozilla.org).
---
- hosts: reviewboardadm.private.scl3.mozilla.com
  roles:
    - { role: reviewboard-admin, site: reviewboard.mozilla.org }
  vars:
    repo: https://hg.mozilla.org/hgcustom/version-control-tools
    rev: "@"
    vct: /data/reviewboard/src/version-control-tools
    venv: /data/reviewboard/src/reviewboard.mozilla.org/venv
    python: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/python
    easy_install: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/easy_install
    rbsite: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/rb-site
    sitehome: /data/reviewboard/src/reviewboard.mozilla.org/reviewboard
  tasks:
    - name: notify IRC a deployment has been started
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#mozreview"
           nick=mozreview-deploy-bot
           color=red
           msg="Production deployment of MozReview initiated"

    - include: tasks/install-mozreview.yml

    - name: deploy code to web servers
      command: /data/reviewboard/deploy -v reviewboard.mozilla.org

# TODO: serialize and integrate with load balancer management
- hosts: rbweb-prod
  tasks:
    - name: restart memcached
      service: name=memcached state=restarted

    - name: restart httpd
      service: name=httpd state=restarted

- hosts: reviewboardadm.private.scl3.mozilla.com
  tasks:
    - name: notify IRC that the deployment has finished
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#mozreview"
           nick=mozreview-deploy-bot
           color=red
           msg="Production deployment of MozReview complete"
