# This playbook is used to update the production deployment of
# MozReview (reviewboard.mozilla.org).
---
- hosts: reviewboardadm.private.scl3.mozilla.com
  roles:
    - { role: reviewboard-admin, site: reviewboard.mozilla.org }
  vars:
    repo: https://hg.mozilla.org/hgcustom/version-control-tools
    rev: "@"
    vct: /data/reviewboard/src/version-control-tools
    venv: /data/reviewboard/src/reviewboard.mozilla.org/venv
    python: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/python
    easy_install: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/easy_install
    rbsite: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/rb-site
    sitehome: /data/reviewboard/src/reviewboard.mozilla.org/reviewboard
    djblets_version: 0.8.19
    rb_version: 2.0.16
  tasks:
    - name: notify IRC a deployment has been started
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#mozreview"
           nick=mozreview-deploy-bot
           color=red
           msg="Production deployment of MozReview initiated"

    - include: tasks/install-mozreview.yml

    - name: stage code for deployment
      command: /usr/bin/rsync -aq --exclude '.git*' --exclude '.hg*' --delete /data/reviewboard/src/ /data/reviewboard/www/

- hosts: rbweb-prod
  serial: 1
  vars_prompt:
  - name: ldap_username
    prompt: "What is your Mozilla LDAP username?"
    private: no

  - name: ldap_password
    prompt: "What is your Mozilla LDAP password?"
    private: yes

  pre_tasks:
    - name: take node out of load balancer
      stingray_node:
        pool: "reviewboard.mozilla.org-http"
        node: "{{ inventory_hostname }}:80"
        state: draining
        url: https://zlb1.ops.scl3.mozilla.com:9070/
        username: "{{ ldap_username }}"
        password: "{{ ldap_password }}"
      delegate_to: 127.0.0.1

    - name: wait for HTTP server to drain
      apache_worker_drain: url=http://localhost/server-status timeout=300

  tasks:
    - name: sync code from admin node
      command: /data/bin/update-www.sh reviewboard.mozilla.org

    - name: restart memcached
      service: name=memcached state=restarted

    - name: restart httpd
      service: name=httpd state=restarted

  post_tasks:
    - name: wait for HTTP server to become available
      wait_for: port=80

    - name: prime HTTP server
      shell: "for n in `seq 20`; do curl -H 'Host: reviewboard.mozilla.org' http://localhost/r/ > /dev/null; done"

    - name: add node back in load balancer
      stingray_node:
        pool: "reviewboard.mozilla.org-http"
        node: "{{ inventory_hostname }}:80"
        state: active
        url: https://zlb1.ops.scl3.mozilla.com:9070/
        username: "{{ ldap_username }}"
        password: "{{ ldap_password }}"
      delegate_to: 127.0.0.1

    # We should ideally send HTTP requests through load balancer until
    # we see a request on the origin server.
    - name: wait for load balancer to re-add node
      pause: seconds=15

# TODO this server isn't playing well with Ansible, likely due to pash
# interaction.
#- hosts: reviewboard-hg1.dmz.scl3.mozilla.com
#  tasks:
#  - name: update v-c-t repo
#    hg: repo={{ repo }}
#        dest=/repo/hg/version-control-tools
#        revision={{ rev }}
#        force=yes
#        purge=yes

- hosts: reviewboardadm.private.scl3.mozilla.com
  tasks:
    - name: notify IRC that the deployment has finished
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#mozreview"
           nick=mozreview-deploy-bot
           color=red
           msg="Production deployment of MozReview complete"
