# This playbook is used to update the development MozReview service.
---
- hosts: reviewboard1.dev.webapp.scl3.mozilla.com
  vars:
    rev: "@"
    repo: https://hg.mozilla.org/hgcustom/version-control-tools
    sitehome: /data/www/reviewboard-dev.allizom.org/reviewboard
    venv: /data/www/reviewboard-dev.allizom.org/venv
    rb_vct: /data/www/reviewboard-dev.allizom.org/version-control-tools
    pip: /data/www/reviewboard-dev.allizom.org/venv/bin/pip
    easy_install: /data/www/reviewboard-dev.allizom.org/venv/bin/easy_install
    python: /data/www/reviewboard-dev.allizom.org/venv/bin/python
    rbsite: /data/www/reviewboard-dev.allizom.org/venv/bin/rb-site
  roles:
    - rbweb
    - { role: mozreview-virtualenv, venv: /data/www/reviewboard-dev.allizom.org/venv }
  tasks:
  - name: install system packages
    yum: name={{ item }} state=present
    with_items:
      - httpd
      - httpd-devel
      - openldap-devel
      - python27
      - python27-devel
      - sudo
      - rsyslog
      - tar

  - name: download Mozilla rpms
    get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS6/{{ item.path }}
             dest=/var/tmp/{{ item.path }}
             sha256sum={{ item.sha256 }}
    with_items:
      - { path: mercurial-3.7.2-1.x86_64.rpm, sha256: cc67d5809571e706268a675d6bae9d1dc6baa2f4fda0d94dd2b90b8f8421d510 }

  - name: install Mozilla rpms
    command: yum localinstall -y /var/tmp/mercurial-3.7.2-1.x86_64.rpm

  - name: create virtualenv for hgweb
    include: tasks/virtualenv.yml
             venv=/repo/hg/venv_hgweb
             requirements=../roles/hg-reviewboard/files/requirements-hgweb.txt

  - name: create virtualenv for pash
    include: tasks/virtualenv.yml
             venv=/repo/hg/venv_pash
             requirements=../roles/hg-reviewboard/files/requirements-pash.txt

  # pash is a collection of Python files handling SSH connections. They behave
  # like a Python module but are installed not as such for historical reasons.
  - name: install pash
    copy: src={{ vct }}/hgserver/pash/{{ item }}
          dest=/usr/local/bin/{{ item }}
          owner=root
          group=root
          mode=0755
    with_items:
      # Install pash.py first to ensure SSH root login works.
      - pash.py
      - hg_helper.py
      - ldap_helper.py
      - pash_wrapper
      - repo_group.py
      - sh_helper.py

  - name: Upgrade the Review Board site
    command: "{{ rbsite }} upgrade {{ sitehome }}"
    register: site_upgrade

  - name: Display any manual upgrade steps
    when: "not (site_upgrade.stdout_lines[-1] == 'Upgrade complete!')"
    debug: msg={{ site_upgrade.stdout }}

  - include: tasks/install-mozreview.yml

  - name: Set proper file permissions for web files
    file: path={{ sitehome }}/htdocs/static/ext owner=apache group=apache recurse=true

  - name: Restart httpd
    service: name=httpd state=restarted

  - name: update v-c-t repo
    hg: repo={{ repo }}
        dest=/repo/hg/version-control-tools
        revision={{ rev }}
        force=yes
        purge=yes

  - name: delete ignored files from version-control-tools repo
    command: "{{ venv }}/bin/hg --config extensions.purge= -R /repo/hg/version-control-tools purge --all"
