# This playbook is used to update the production deployment of
# MozReview (reviewboard.mozilla.org).
---
- hosts: reviewboardadm.private.scl3.mozilla.com
  roles:
    - { role: reviewboard-admin, site: reviewboard.mozilla.org }
  vars:
    repo: https://hg.mozilla.org/hgcustom/version-control-tools
    rev: "@"
    rb_vct: /data/reviewboard/src/version-control-tools
    venv: /data/reviewboard/src/reviewboard.mozilla.org/venv
    python: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/python
    easy_install: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/easy_install
    rbsite: /data/reviewboard/src/reviewboard.mozilla.org/venv/bin/rb-site
    sitehome: /data/reviewboard/src/reviewboard.mozilla.org/reviewboard
  tasks:
    - name: notify IRC a deployment has been started
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#mozreview"
           nick=mozreview-deploy-bot
           color=red
           msg="Production deployment of MozReview initiated from rev {{ lookup('file', '../.vctnode') }}"

    - include: tasks/install-mozreview.yml

    - name: stage code for deployment
      command: /usr/bin/rsync -aq --exclude '.git*' --exclude '.hg*' --delete /data/reviewboard/src/ /data/reviewboard/www/

- hosts: reviewboard-hg1.dmz.scl3.mozilla.com
  pre_tasks:
    # Until we integrate secrets with Ansible, the LDAP config is
    # pre-defined on the server.
    - name: capture LDAP config
      slurp: src=/etc/mercurial/ldap.json
      register: ldap_config

    # Ditto for the username and password of the privileged MozReview
    # account
    - name: capture MozReview credentials
      slurp: src=/etc/mercurial/mozreview.json
      register: mozreview_config

  roles:
    - {
        role: hg-reviewboard,
        domain: "reviewboard-hg.mozilla.org",
        bind_dn: "{{ (ldap_config.content | b64decode | from_json).username }}",
        bind_pw: "{{ (ldap_config.content | b64decode | from_json).password }}",
        ldap_uri: "{{ (ldap_config.content | b64decode | from_json).url }}",
        reviewboard_url: "https://reviewboard.mozilla.org",
        reviewboard_username: "{{ (mozreview_config.content | b64decode | from_json).username }}",
        reviewboard_password: "{{ (mozreview_config.content | b64decode | from_json).password }}",
      }

- hosts: rbweb-prod
  serial: 1
  vars_prompt:
  - name: ldap_username
    prompt: "What is your Mozilla LDAP username?"
    private: no

  - name: ldap_password
    prompt: "What is your Mozilla LDAP password?"
    private: yes

  pre_tasks:
    - name: take node out of load balancer
      stingray_node:
        pool: "reviewboard.mozilla.org-http"
        node: "{{ inventory_hostname }}:80"
        state: draining
        url: https://zlb1.ops.scl3.mozilla.com:9070/
        username: "{{ ldap_username }}"
        password: "{{ ldap_password }}"
      delegate_to: 127.0.0.1

    - name: wait for HTTP server to drain
      apache_worker_drain: url=http://localhost/server-status timeout=300

  tasks:
    - name: sync code from admin node
      command: /data/bin/update-www.sh reviewboard.mozilla.org

    # We previously restarted memcached here. But this appears to clear
    # all sessions and logs people out. This is super annoying,
    # especially when we deploy multiple times per day. So we stopped
    # doing it.

    - name: restart httpd
      service: name=httpd state=restarted

  post_tasks:
    - name: wait for HTTP server to become available
      wait_for: port=80

    - name: prime HTTP server
      shell: "for n in `seq 20`; do curl -H 'Host: reviewboard.mozilla.org' http://localhost/r/ > /dev/null; done"

    - name: add node back in load balancer
      stingray_node:
        pool: "reviewboard.mozilla.org-http"
        node: "{{ inventory_hostname }}:80"
        state: active
        url: https://zlb1.ops.scl3.mozilla.com:9070/
        username: "{{ ldap_username }}"
        password: "{{ ldap_password }}"
      delegate_to: 127.0.0.1

    # We should ideally send HTTP requests through load balancer until
    # we see a request on the origin server.
    - name: wait for load balancer to re-add node
      pause: seconds=15

- hosts: reviewboardadm.private.scl3.mozilla.com
  gather_facts: no
  tasks:
    - name: notify IRC that the deployment has finished
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#mozreview"
           nick=mozreview-deploy-bot
           color=red
           msg="Production deployment of MozReview complete"
