---
- hosts: localhost
  roles:
    - docker-hg-ssh
  vars:
    ldap_uri: ldap://localhost/
    bind_dn: cn=admin,dc=mozilla
    bind_pw: password
    home_attribute: fakeHome
    zk_listen_on_all_ips: true
