---
- hosts: hgssh1.dmz.scl3.mozilla.com
  tasks:
    - name: notify IRC of deployment
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#vcs"
           nick=hg-deploy-bot
           color=red
           msg="Starting deploy of hooks and extensions to hg.mozilla.org from rev {{ lookup('file', '../.vctnode') }}"
      delegate_to: 127.0.0.1
      run_once: true

    # We need to write this out on clients.
    - name: capture mirror key
      slurp: src=/etc/mercurial/mirror
      register: mirror_private_key

    - name: capture host key
      slurp: src=/etc/ssh/ssh_host_rsa_key.pub
      register: mirror_host_key

- hosts: hgweb-prod
  roles:
    - { role: hg-web,
        # We have to use hostvars to reference variables on other hosts.
        # slurp captures content in base64 encoded form. Decode it
        # before it is passed in.
        mirror_private_key: "{{ hostvars['hgssh1.dmz.scl3.mozilla.com'].mirror_private_key.content | b64decode }}",
        mirror_host_key: "{{ hostvars['hgssh1.dmz.scl3.mozilla.com'].mirror_host_key.content | b64decode }}",
        # hg-zlb.vips.scl3.mozilla.com resolves to multiple IPs.
        mirror_ips: ["63.245.215.25", "63.245.215.102"],
      }

- hosts: hgssh1.dmz.scl3.mozilla.com
  pre_tasks:
    # Until we integrate secrets with Ansible, the LDAP config is
    # pre-defined on the server.
    - name: capture LDAP config
      slurp: src=/etc/mercurial/ldap.json
      register: ldap_config

  roles:
    - {
        role: hg-ssh,
        bind_dn: "{{ (ldap_config.content | b64decode | from_json).username }}",
        bind_pw: "{{ (ldap_config.content | b64decode | from_json).password }}",
        ldap_uri: "{{ (ldap_config.content | b64decode | from_json).url }}",
      }

  tasks:
    # Install CRON to generate Mercurial bundle files. This only needs
    # to run on the master.
    - include: tasks/hgmo-bundle-cron.yml
      when: ansible_hostname == "hgssh1"

    - name: notify IRC of deployment
      irc: server=irc.mozilla.org
           port=6697
           use_ssl=true
           channel="#vcs"
           nick=hg-deploy-bot
           color=red
           msg="Finished deploy of hooks and extensions to hg.mozilla.org"
      delegate_to: 127.0.0.1
      run_once: true
