# This playbook is used to update the development MozReview service.
---
- hosts: reviewboard1.dev.webapp.scl3.mozilla.com
  vars:
    rev: "@"
    repo: https://hg.mozilla.org/hgcustom/version-control-tools
    sitehome: /data/www/reviewboard-dev.allizom.org/reviewboard
    venv: /data/www/reviewboard-dev.allizom.org/venv
    vct: /data/www/reviewboard-dev.allizom.org/version-control-tools
    pip: /data/www/reviewboard-dev.allizom.org/venv/bin/pip
    easy_install: /data/www/reviewboard-dev.allizom.org/venv/bin/easy_install
    python: /data/www/reviewboard-dev.allizom.org/venv/bin/python
    rbsite: /data/www/reviewboard-dev.allizom.org/venv/bin/rb-site
    djblets_version: 0.8.20
    rb_version: 2.0.17
  tasks:
  - name: Install RBTools
    command: "{{ pip }} install --allow-external RBTools --allow-unverified RBTools --upgrade RBTools==0.6.1"

  - name: Install Review Board and Djblets
    command: "{{ easy_install }} -U Djblets=={{ djblets_version }} ReviewBoard=={{ rb_version }}"

  - name: Upgrade the Review Board site
    command: "{{ rbsite }} upgrade {{ sitehome }}"
    register: site_upgrade

  - name: Display any manual upgrade steps
    when: "not (site_upgrade.stdout_lines[-1] == 'Upgrade complete!')"
    debug: msg={{ site_upgrade.stdout }}

  - include: tasks/install-mozreview.yml

  - name: Set proper file permissions for web files
    file: path={{ sitehome }}/htdocs/static/ext owner=apache group=apache recurse=true

  - name: Restart memcached
    service: name=memcached state=restarted

  - name: Restart httpd
    service: name=httpd state=restarted

  - name: update v-c-t repo
    hg: repo={{ repo }}
        dest=/repo/hg/version-control-tools
        revision={{ rev }}
        force=yes
        purge=yes
