---
- name: create hg user
  user: name=hg uid=500

- name: install system packages
  command: yum install -y httpd lockfile-progs mod_wsgi openssh-clients openssh-server python-pygments python-simplejson python-argparse syslog

- name: install Mercurial package
  command: yum localinstall -y https://people.mozilla.org/~gszorc/mercurial-3.3.2-0.x86_64.rpm

- name: create directories for hg files
  file: path={{ item }} state=directory owner=hg group=hg mode=0755
  with_items:
    - /repo_local/mozilla/mozilla

- name: symlink /repo to /repo_local
  file: src=/repo_local dest=/repo state=link

- name: install httpd.conf
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf

- name: install vhost config
  copy: src=vhost.conf dest=/etc/httpd/conf.d/hg-vhost.conf

- name: install wsgi config
  copy: src=mod_wsgi.conf dest=/etc/httpd/conf.d/wsgi.conf

- name: create httpd log directory
  file: path=/var/log/httpd/hg state=directory

- name: install global hgrc config
  copy: src=hgrc dest=/etc/mercurial/hgrc

- name: install mirroring scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
    - lockfile
    - mirror-pull
    - repo-group

- name: create .ssh directory for hg user
  file: path=/home/hg/.ssh owner=hg group=hg mode=0750 state=directory

- name: install ssh config file
  copy: src=ssh-config dest=/home/hg/.ssh/config owner=hg group=hg mode=0640

- name: ensure hg user known hosts file exists
  file: path=/home/hg/.ssh/known_hosts state=touch owner=hg group=hg mode=0640

- include: ../../../tasks/hgmo-extensions.yml

- name: install hgweb wsgi files
  copy: src={{ item }} dest=/repo/hg/webroot_wsgi/{{ item }} owner=hg group=hg
  with_items:
    - hgweb.config
    - hgweb.wsgi

- name: install Docker support files
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - entrypoint.py
    - run.sh
    - set-mirror-key.py
