---
- name: create hg user
  user: name=hg uid=500

- name: install system packages
  command: yum install -y httpd lockfile-progs mod_wsgi openssh-clients openssh-server python-simplejson python-argparse syslog

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.
- name: download Mercurial package
  get_url: url=https://people.mozilla.org/~gszorc/mercurial-3.4.1-0.x86_64.rpm
           dest=/var/tmp/mercurial-3.4.1-0.x86_64.rpm
           sha256sum=4e6190232ae217aacc894c0baf8e61900cb55d4ee0406a09a22b70cb9c6dfbd0

- name: install Mercurial package
  command: yum localinstall -y /var/tmp/mercurial-3.4.1-0.x86_64.rpm

- name: install httpd.conf
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf

- name: install vhost config
  copy: src=vhost.conf dest=/etc/httpd/conf.d/hg-vhost.conf

- name: install wsgi config
  copy: src=mod_wsgi.conf dest=/etc/httpd/conf.d/wsgi.conf

- name: create httpd log directory
  file: path=/var/log/httpd/hg state=directory

- name: install global hgrc config
  copy: src=hgrc dest=/etc/mercurial/hgrc

- name: install mirroring scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
    - lockfile
    - mirror-pull
    - repo-group

- include: ../../../tasks/hgmo-extensions.yml

- name: install hgweb wsgi files
  copy: src={{ item }} dest=/repo/hg/webroot_wsgi/{{ item }} owner=hg group=hg
  with_items:
    - hgweb.config
    - hgweb.wsgi

- name: install Docker support files
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - entrypoint.py
    - run.sh
    - set-mirror-key.py
