---

- name: download Node rpm setup script
  get_url: url=https://raw.githubusercontent.com/nodesource/distributions/9021c9def5fbbf81f610cb61c171f97cb9755542/rpm/setup
           dest=/var/tmp/node-setup
           sha256sum=982db69277a23d5be5e8de6524dad85178b682c6e54c9dbe674cb3fa705e22a8

- name: configure Node sources
  command: /bin/bash /var/tmp/node-setup
           creates=/etc/yum.repos.d/nodesource-el.repo

- name: install dependency packages
  yum: name={{ item }}
  with_items:
    - httpd-devel
    - libjpeg-turbo-devel
    - mysql-devel
    - nodejs
    - npm
    - python-devel
    - openldap-devel
    - python27
    - tar
    - zlib-devel

# This is required for building Review Board extensions.
# Make it conditional because it takes a long time to run, making building
# painfully slow.
- name: install Node packages
  command: /usr/bin/npm install -g less uglify-js
           creates=/usr/bin/lessc

# TODO all this code can change to use virtualenv.yml once we switch to
# Python 2.7.

- name: download python packaging tools
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/{{ item.path }}
           dest=/var/tmp/{{ item.path }}
           sha256sum={{ item.shasum }}
  with_items:
    - { path: get-pip-8.0.3.py, shasum: 85a499fbd52603045812df8ca1c0491483e5f28eca15a3b3025507a66f225acf }
    - { path: virtualenv-14.0.6.tar.gz, shasum: 1ffb6a02d8999e9c97ad8f04b1d2ba44421dfb8f8a98b54aea5c6fdfb53bc526 }

- name: extract virtualenv package
  unarchive: src=/var/tmp/virtualenv-14.0.6.tar.gz
             dest=/var/tmp
             copy=no

- name: install latest packaging wheels to virtualenv package
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/{{ item.path }}
           dest=/var/tmp/virtualenv-14.0.6/virtualenv_support/{{ item.path }}
           sha256sum={{ item.shasum }}
  with_items:
    - { path: pip-8.0.3-py2.py3-none-any.whl, shasum: b0335bc837f9edb5aad03bd43d0973b084a1cbe616f8188dc23ba13234dbd552 }
    - { path: setuptools-20.1.1-py2.py3-none-any.whl, shasum: dfdbc643f8900d9e617e48a42ae389aa18fd6fbd2846f24f2a4678b8d9412acb }

- name: install virtualenv package
  command: /usr/bin/python setup.py install
           chdir=/var/tmp/virtualenv-14.0.6
           creates=/usr/bin/virtualenv

- name: create directory structure
  file: path={{ venv }}
        state=directory
        owner=root
        group=root

- name: create virtualenv
  command: /usr/bin/virtualenv {{ venv }} creates={{ venv }}/bin/python

- name: upgrade python packaging packages
  command: "{{ venv }}/bin/python /var/tmp/get-pip-8.0.3.py --upgrade --no-index --find-links /var/tmp/virtualenv-14.0.6/virtualenv_support pip setuptools wheel"

- name: copy requirements.txt
  copy: src=requirements.txt
        dest={{ venv }}/requirements.txt
        owner=root
        group=root

- name: populate virtualenv
  command: "{{ venv }}/bin/pip install --require-hashes -r {{ venv }}/requirements.txt"
