---
venv_hgweb: /repo/hg/venv_hgweb
venv_replication: /repo/hg/venv_replication
venv_tools: /repo/hg/venv_tools
wsgi_processes: "{{ ansible_processor_cores * 8 }}" # usually 48
httpd_start_servers: 8
httpd_min_spare_servers: 5
httpd_max_spare_servers: 20
httpd_server_limit: "{{ ansible_processor_cores * 10 }}" # 60 or 120
httpd_max_clients: "{{ ansible_processor_cores * 10 }}" # 60 or 120
httpd_max_requests_per_child: 4000

# Used for replication
mirror_source: hg.mozilla.org
mirror_ssh_user: vcs-sync@mozilla.com
mirror_ips: []
mirror_host_key: "undefined"
mirror_private_key: "undefined"
