---
wsgi_processes: "{{ ansible_processor_cores * 4 }}" # usually 24
httpd_start_servers: 8
httpd_min_spare_servers: 5
httpd_max_spare_servers: 20
httpd_server_limit: "{{ ansible_processor_cores * 5 }}" # 30 or 60
httpd_max_clients: "{{ ansible_processor_cores * 5 }}" # 30 or 60
httpd_max_requests_per_child: 4000

# Used for replication
mirror_source: hg.mozilla.org
mirror_ssh_user: vcs-sync@mozilla.com
mirror_ips: []
mirror_host_key: "undefined"
mirror_private_key: "undefined"

# Assume the chroot files aren't available unless told otherwise (since
# it is uncommon to deploy them).
chroot_mozbuild_exists: False
